using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using SD.FolderManagement.Utility;
using UnityEditor;
using UnityEngine;

namespace SD.FolderManagement {

    public class FolderManager {

        //Defaults
        private const string PLUGIN_NAME = "FolderManager";
        private const string GENERATED_FOLDER_NAME = "AutoGenerated";
        private const string DATA_FOLDER_NAME = "Data";

        public static void Initialize() {

        }

        #region Creating the workspace

        public static bool Create() {

            if (Exists()) return false;

            if (DirectoryUtility.Create(GeneratedFolderPath())) {
                if (!DirectoryUtility.Create(DataFolderPath())) {
                    return false;
                }
            }

            AssetDatabase.Refresh();
            return true;
        }

        #region Lookups

        public static bool Exists() {
            return DirectoryUtility.ExistsRelative("/" + PLUGIN_NAME + "/" + GENERATED_FOLDER_NAME);
        }

        public static string PluginFolderPath() {
            return DirectoryUtility.GetAppDataPath() + "/" + PLUGIN_NAME;
        }

        public static string GeneratedFolderPath() {
            return PluginFolderPath() + "/" + GENERATED_FOLDER_NAME;
        }

        public static string DataFolderPath() {
            return GeneratedFolderPath() + "/" + DATA_FOLDER_NAME;
        }

        #endregion

        #endregion
    }
}

